//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMedico
    {
        public int id_historial { get; set; }
        public int id_paciente { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
