//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public int id_receta { get; set; }
        public int id_diagnostico { get; set; }
        public int id_medicamento { get; set; }
        public string dosis { get; set; }
        public string duracion { get; set; }
    
        public virtual Diagnostico Diagnostico { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
